## Visual puppet for a gateway-driven entity.
## Buffers the last two base_pose samples and interpolates between them,
## delayed by one state interval (standard entity interpolation).
## F8: Body mesh from generated URDF visual JSON (not hand-copied sizes).
## Team look: tint chassis + billboard tag by entity_id (A/B).
class_name MWMechPuppet
extends Node3D

## Must be @export so Web/macOS export packs the scene override.
@export var entity_id: String = "mech_player"
## F8: generated by mujoco/scripts/urdf_to_mjcf_planar.py from DiffBot URDF.
@export var visual_json_path: String = "res://assets/mech/diffbot_visual.json"
## Workshop lookalike: hide A/B tag and platformer arrow.
@export var show_team_tag: bool = true
@export var show_front_arrow: bool = true
## Race chassis has no arm in MJCF — skip industrial arm mesh.
@export var show_arm: bool = true
## Race: Kenney Car Kit skin (viewer_only; MuJoCo still DiffBot).
@export var use_kenney_car: bool = false
## If alpha > 0, overrides TEAM_COLORS chassis tint (e.g. industrial orange).
@export var chassis_tint_override: Color = Color(0, 0, 0, 0)
var interp_delay := 0.05

## entity_id → chassis albedo (shared city room A–E).
const TEAM_COLORS := {
	"mech_player": Color(0.22, 0.62, 0.95),
	"mech_player_b": Color(0.95, 0.48, 0.18),
	"mech_player_c": Color(0.35, 0.82, 0.45),
	"mech_player_d": Color(0.85, 0.75, 0.25),
	"mech_player_e": Color(0.75, 0.4, 0.9),
	"mech_player_f": Color(0.95, 0.35, 0.55),
}
const TEAM_TAGS := {
	"mech_player": "A",
	"mech_player_b": "B",
	"mech_player_c": "C",
	"mech_player_d": "D",
	"mech_player_e": "E",
	"mech_player_f": "F",
}
const WHEEL_COLOR := Color(0.0, 0.0, 0.0)
const CASTER_COLOR := Color(1.0, 1.0, 1.0)
const FRONT_ARROW_SCENE := preload("res://assets/platformer/arrow.glb")
const FRONT_ARROW_POS := Vector3(0.55, 0.55, 0.0)
## Kenney Car Kit (CC0) — one body style per race slot; baked colormap colors.
const KENNEY_CAR_DIR := "res://assets/kenney_car/"
const KENNEY_CAR_BY_ENTITY := {
	"mech_player": "race.glb",
	"mech_player_b": "race-future.glb",
	"mech_player_c": "sedan-sports.glb",
	"mech_player_d": "hatchback-sports.glb",
	"mech_player_e": "police.glb",
	"mech_player_f": "taxi.glb",
}
## Car forward is typically -Z; MW puppet forward is +X.
const KENNEY_CAR_YAW := -PI * 0.5
const KENNEY_CAR_SCALE := Vector3(0.9, 0.9, 0.9)
## Authority pose is chassis center (~0.5 m); Kenney origin is ground.
const KENNEY_CAR_Y := -0.42
## Industrial arm look (viewer_only; kinematics still follow MJCF pivots).
const ARM_METAL := Color(0.62, 0.65, 0.7)
const ARM_DARK := Color(0.2, 0.22, 0.26)
const ARM_ACCENT := Color(0.95, 0.52, 0.12)
const GRIPPER_COLOR := Color(0.88, 0.9, 0.93)

var _prev_pos := Vector3.ZERO
var _prev_yaw := 0.0
var _prev_time := -1.0
var _next_pos := Vector3.ZERO
var _next_yaw := 0.0
var _next_time := -1.0
var _has_state := false
var _sim_now := 0.0
var _wall_at_last_state := 0.0
## Last authority pose (MW frame) for HUD/debug.
var last_mw_x := 0.0
var last_mw_y := 0.0
var last_mw_yaw := 0.0
var _cart_built := false
var _arm_built := false
var _kenney_car_id := ""
var _wheel_joint_names: PackedStringArray = PackedStringArray()
var _arm_yaw: Node3D
var _arm_shoulder: Node3D
var _arm_elbow: Node3D
var _finger_l: Node3D
var _finger_r: Node3D


func _ready() -> void:
	ensure_planar_cart_visual()
	if show_arm and not use_kenney_car:
		_ensure_arm_visual()
	_ensure_front_arrow()
	apply_team_look()


func _ensure_front_arrow() -> void:
	"""Attach a forward marker on +X (MW forward); follows this puppet."""
	var existing := get_node_or_null("FrontArrow") as Node3D
	if not show_front_arrow:
		if existing != null:
			existing.visible = false
		return
	if existing != null:
		existing.visible = true
		return
	var arrow: Node3D = FRONT_ARROW_SCENE.instantiate() as Node3D
	arrow.name = "FrontArrow"
	arrow.position = FRONT_ARROW_POS
	add_child(arrow)


func _mw_to_local(p: Vector3) -> Vector3:
	"""Map MW/URDF Z-up point into Godot local (Y-up) on this puppet."""
	return Vector3(p.x, p.z, -p.y)


func _mw_size_to_local(s: Vector3) -> Vector3:
	"""Map MW full-edge box size (x,y,z) → Godot BoxMesh size (x,y,z)."""
	return Vector3(s.x, s.z, s.y)


func _vec3_from_array(arr: Variant, fallback: Vector3) -> Vector3:
	"""Parse a 3-number JSON array into Vector3."""
	if typeof(arr) != TYPE_ARRAY:
		return fallback
	var a: Array = arr
	if a.size() < 3:
		return fallback
	return Vector3(float(a[0]), float(a[1]), float(a[2]))


func _load_visual_spec() -> Dictionary:
	"""Load F8 URDF visual JSON; empty dict if missing/invalid."""
	if visual_json_path.is_empty() or not FileAccess.file_exists(visual_json_path):
		push_warning("MWMechPuppet: visual JSON missing: %s" % visual_json_path)
		return {}
	var raw := FileAccess.get_file_as_string(visual_json_path)
	var parsed: Variant = JSON.parse_string(raw)
	if typeof(parsed) != TYPE_DICTIONARY:
		push_warning("MWMechPuppet: visual JSON invalid: %s" % visual_json_path)
		return {}
	return parsed


func ensure_planar_cart_visual() -> void:
	"""Build/replace Body from F8 visual JSON or Kenney car skin (idempotent)."""
	if use_kenney_car:
		_ensure_kenney_car_visual()
		return
	if _cart_built and get_node_or_null("Body/Chassis") != null:
		return
	var spec := _load_visual_spec()
	var chassis_size := _vec3_from_array(
		(spec.get("chassis", {}) as Dictionary).get("size", []),
		Vector3(1.0, 1.0, 0.5)
	)
	var wheels: Array = spec.get("wheels", [])
	var casters: Array = spec.get("casters", [])

	var old := get_node_or_null("Body")
	if old != null:
		remove_child(old)
		old.free()
	var body := Node3D.new()
	body.name = "Body"
	add_child(body)

	var chassis := MeshInstance3D.new()
	chassis.name = "Chassis"
	var box := BoxMesh.new()
	box.size = _mw_size_to_local(chassis_size)
	chassis.mesh = box
	chassis.set_meta("team_tint", true)
	body.add_child(chassis)

	var ci := 0
	for citem in casters:
		if typeof(citem) != TYPE_DICTIONARY:
			continue
		var cd: Dictionary = citem
		var caster := MeshInstance3D.new()
		caster.name = "Caster_%d" % ci
		var sphere := SphereMesh.new()
		var cr := float(cd.get("radius", 0.15))
		sphere.radius = cr
		sphere.height = cr * 2.0
		caster.mesh = sphere
		caster.position = _mw_to_local(_vec3_from_array(cd.get("pos", []), Vector3.ZERO))
		_tint_mesh(caster, CASTER_COLOR)
		body.add_child(caster)
		ci += 1

	_wheel_joint_names = PackedStringArray()
	var i := 0
	for witem in wheels:
		if typeof(witem) != TYPE_DICTIONARY:
			continue
		var wd: Dictionary = witem
		var wheel := MeshInstance3D.new()
		wheel.name = "Wheel_%d" % i
		var cyl := CylinderMesh.new()
		var wr := float(wd.get("radius", 0.15))
		var wl := float(wd.get("length", 0.2))
		cyl.top_radius = wr
		cyl.bottom_radius = wr
		cyl.height = wl
		wheel.mesh = cyl
		wheel.position = _mw_to_local(_vec3_from_array(wd.get("pos", []), Vector3.ZERO))
		# Cylinder default axis = Godot +Y; Rx(90) → axle along Godot +Z (MW ±Y).
		wheel.basis = Basis(Vector3.RIGHT, PI * 0.5)
		_tint_mesh(wheel, WHEEL_COLOR)
		body.add_child(wheel)
		_wheel_joint_names.append(str(wd.get("joint", "left_wheel_joint")))
		i += 1

	_cart_built = true
	_kenney_car_id = ""
	_arm_built = false
	if show_arm:
		_ensure_arm_visual()


func _ensure_kenney_car_visual() -> void:
	"""Viewer-only Kenney car body; skip DiffBot box/wheels/arm."""
	if _cart_built and get_node_or_null("Body/KenneyCar") != null and _kenney_car_id == entity_id:
		return
	var old := get_node_or_null("Body")
	if old != null:
		remove_child(old)
		old.free()
	var body := Node3D.new()
	body.name = "Body"
	add_child(body)
	var fname := str(KENNEY_CAR_BY_ENTITY.get(entity_id, "race.glb"))
	var path := KENNEY_CAR_DIR + fname
	if not ResourceLoader.exists(path):
		push_warning("MWMechPuppet: Kenney car missing: %s" % path)
		_cart_built = false
		_kenney_car_id = ""
		return
	var packed := load(path) as PackedScene
	if packed == null:
		push_warning("MWMechPuppet: Kenney car load failed: %s" % path)
		_cart_built = false
		_kenney_car_id = ""
		return
	var car: Node3D = packed.instantiate() as Node3D
	car.name = "KenneyCar"
	car.position = Vector3(0.0, KENNEY_CAR_Y, 0.0)
	car.rotation.y = KENNEY_CAR_YAW
	car.scale = KENNEY_CAR_SCALE
	body.add_child(car)
	_wheel_joint_names = PackedStringArray()
	_cart_built = true
	_kenney_car_id = entity_id
	_arm_built = false


func _ensure_arm_visual() -> void:
	"""V2b: industrial-looking geometric arm under Body (same pivots as MJCF)."""
	ensure_planar_cart_visual()
	var body := get_node_or_null("Body") as Node3D
	if body == null:
		return
	if _arm_built and body.get_node_or_null("ArmMount") != null:
		return
	var old := body.get_node_or_null("ArmMount")
	if old != null:
		body.remove_child(old)
		old.free()

	var mount := Node3D.new()
	mount.name = "ArmMount"
	# MJCF arm_base at chassis (0.15, 0, 0.25) → Godot (x, z, -y)
	mount.position = Vector3(0.15, 0.25, 0.0)
	body.add_child(mount)

	# Pedestal on chassis
	_arm_add_cyl(mount, "Base", 0.09, 0.06, Vector3(0.0, 0.03, 0.0), Vector3.ZERO, ARM_DARK, 0.55, 0.35)

	_arm_yaw = Node3D.new()
	_arm_yaw.name = "ArmYaw"
	mount.add_child(_arm_yaw)
	_arm_add_cyl(_arm_yaw, "YawColumn", 0.055, 0.22, Vector3(0.0, 0.13, 0.0), Vector3.ZERO, ARM_METAL, 0.7, 0.28)
	_arm_add_cyl(_arm_yaw, "YawRing", 0.078, 0.04, Vector3(0.0, 0.22, 0.0), Vector3.ZERO, ARM_ACCENT, 0.35, 0.45)

	_arm_shoulder = Node3D.new()
	_arm_shoulder.name = "ArmShoulder"
	_arm_shoulder.position = Vector3(0.0, 0.24, 0.0)
	_arm_yaw.add_child(_arm_shoulder)
	# Hub along Godot Z (MW hinge +Y)
	_arm_add_cyl(_arm_shoulder, "ShoulderHub", 0.07, 0.09, Vector3.ZERO, Vector3(PI * 0.5, 0.0, 0.0), ARM_ACCENT, 0.4, 0.4)
	_arm_add_cyl(_arm_shoulder, "UpperArm", 0.048, 0.36, Vector3(0.18, 0.0, 0.0), Vector3(0.0, 0.0, PI * 0.5), ARM_METAL, 0.75, 0.25)

	_arm_elbow = Node3D.new()
	_arm_elbow.name = "ArmElbow"
	_arm_elbow.position = Vector3(0.36, 0.0, 0.0)
	_arm_shoulder.add_child(_arm_elbow)
	_arm_add_cyl(_arm_elbow, "ElbowHub", 0.06, 0.08, Vector3.ZERO, Vector3(PI * 0.5, 0.0, 0.0), ARM_ACCENT, 0.4, 0.4)
	_arm_add_cyl(_arm_elbow, "ForeArm", 0.042, 0.28, Vector3(0.14, 0.0, 0.0), Vector3(0.0, 0.0, PI * 0.5), ARM_METAL, 0.75, 0.25)

	var wrist := _arm_add_box(_arm_elbow, "Wrist", Vector3(0.06, 0.07, 0.1), Vector3(0.28, 0.0, 0.0), ARM_DARK, 0.5, 0.4)
	wrist.name = "Palm"
	_arm_add_box(_arm_elbow, "PalmPlate", Vector3(0.03, 0.09, 0.14), Vector3(0.3, 0.0, 0.0), ARM_METAL, 0.65, 0.3)

	_finger_l = _arm_add_box(_arm_elbow, "FingerL", Vector3(0.1, 0.028, 0.028), Vector3(0.34, 0.0, 0.05), GRIPPER_COLOR, 0.2, 0.35)
	_finger_r = _arm_add_box(_arm_elbow, "FingerR", Vector3(0.1, 0.028, 0.028), Vector3(0.34, 0.0, -0.05), GRIPPER_COLOR, 0.2, 0.35)
	_arm_add_box(_finger_l, "PadL", Vector3(0.02, 0.032, 0.034), Vector3(0.05, 0.0, 0.0), ARM_ACCENT, 0.15, 0.55)
	_arm_add_box(_finger_r, "PadR", Vector3(0.02, 0.032, 0.034), Vector3(0.05, 0.0, 0.0), ARM_ACCENT, 0.15, 0.55)

	_arm_built = true


func _arm_style(mesh_inst: MeshInstance3D, color: Color, metallic: float, roughness: float) -> void:
	"""Apply metal-ish material for arm parts."""
	var mat := StandardMaterial3D.new()
	mat.albedo_color = color
	mat.metallic = metallic
	mat.roughness = roughness
	mesh_inst.material_override = mat


func _arm_add_cyl(
	parent: Node3D,
	part_name: String,
	radius: float,
	height: float,
	pos: Vector3,
	rot: Vector3,
	color: Color,
	metallic: float,
	roughness: float
) -> MeshInstance3D:
	"""Add a cylinder mesh part under the arm hierarchy."""
	var mi := MeshInstance3D.new()
	mi.name = part_name
	var cyl := CylinderMesh.new()
	cyl.top_radius = radius
	cyl.bottom_radius = radius
	cyl.height = height
	cyl.radial_segments = 16
	mi.mesh = cyl
	mi.position = pos
	mi.rotation = rot
	_arm_style(mi, color, metallic, roughness)
	parent.add_child(mi)
	return mi


func _arm_add_box(
	parent: Node3D,
	part_name: String,
	size: Vector3,
	pos: Vector3,
	color: Color,
	metallic: float,
	roughness: float
) -> MeshInstance3D:
	"""Add a box mesh part under the arm hierarchy."""
	var mi := MeshInstance3D.new()
	mi.name = part_name
	var box := BoxMesh.new()
	box.size = size
	mi.mesh = box
	mi.position = pos
	_arm_style(mi, color, metallic, roughness)
	parent.add_child(mi)
	return mi


func _apply_arm_joints(joints: Variant) -> void:
	"""Drive arm Node3Ds from state.joints (MW hinge Z→Godot Y; MW Y→Godot -Z)."""
	if not show_arm or typeof(joints) != TYPE_DICTIONARY:
		return
	_ensure_arm_visual()
	if _arm_yaw == null:
		return
	var j: Dictionary = joints
	var yaw_q := float(j.get("arm_yaw", 0.0))
	var sh_q := float(j.get("arm_shoulder", 0.0))
	var el_q := float(j.get("arm_elbow", 0.0))
	var grip := float(j.get("gripper", 0.0))
	_arm_yaw.rotation = Vector3(0.0, yaw_q, 0.0)
	# MW hinge axis +Y → Godot -Z
	_arm_shoulder.basis = Basis(Vector3(0.0, 0.0, -1.0), sh_q)
	_arm_elbow.basis = Basis(Vector3(0.0, 0.0, -1.0), el_q)
	if _finger_l != null and _finger_r != null:
		_finger_l.position = Vector3(0.34, 0.0, 0.05 + grip)
		_finger_r.position = Vector3(0.34, 0.0, -0.05 - grip)


func apply_team_look() -> void:
	"""Tint chassis mesh and show A/B billboard from entity_id."""
	ensure_planar_cart_visual()
	_ensure_front_arrow()
	var color: Color = TEAM_COLORS.get(entity_id, Color(0.65, 0.65, 0.68))
	if chassis_tint_override.a > 0.01:
		color = chassis_tint_override
	# Kenney cars keep baked colormap; only DiffBot box gets albedo tint.
	if not use_kenney_car:
		var chassis := get_node_or_null("Body/Chassis") as MeshInstance3D
		if chassis != null:
			_tint_mesh(chassis, color)
		else:
			var body_root := get_node_or_null("Body")
			if body_root is MeshInstance3D:
				_tint_mesh(body_root as MeshInstance3D, color)
			elif body_root != null:
				for child in body_root.find_children("*", "MeshInstance3D", true, false):
					if child.has_meta("team_tint"):
						_tint_mesh(child as MeshInstance3D, color)
	var tag := get_node_or_null("TeamTag") as Label3D
	if not show_team_tag:
		if tag != null:
			tag.visible = false
		return
	if tag == null:
		tag = Label3D.new()
		tag.name = "TeamTag"
		tag.billboard = BaseMaterial3D.BILLBOARD_ENABLED
		tag.font_size = 72
		tag.outline_size = 10
		tag.outline_modulate = Color(0, 0, 0, 0.85)
		tag.position = Vector3(0.0, 1.35 if use_kenney_car else 1.15, 0.0)
		tag.pixel_size = 0.012
		add_child(tag)
	elif use_kenney_car:
		tag.position = Vector3(0.0, 1.35, 0.0)
	MWFonts.apply_label3d(tag)
	tag.visible = true
	tag.text = str(TEAM_TAGS.get(entity_id, "?"))
	tag.modulate = color


func _tint_mesh(mesh_inst: MeshInstance3D, color: Color) -> void:
	"""Apply a simple albedo override."""
	var mat := StandardMaterial3D.new()
	mat.albedo_color = color
	mat.roughness = 0.55
	mat.metallic = 0.15
	mesh_inst.material_override = mat


func apply_state(entity: Dictionary, t_sim: float) -> void:
	"""Push a new authority sample; t_sim must be monotonic for interpolation."""
	var pose: Dictionary = entity.get("base_pose", {})
	last_mw_x = float(pose.get("x", 0.0))
	last_mw_y = float(pose.get("y", 0.0))
	last_mw_yaw = float(pose.get("yaw", 0.0))
	# Fallback if t_sim missing/zero but pose is moving — avoid span<=0 freeze.
	if t_sim <= 0.0 and _next_time >= 0.0:
		t_sim = _next_time + interp_delay
	_sim_now = t_sim
	_wall_at_last_state = Time.get_ticks_msec() / 1000.0
	_prev_pos = _next_pos
	_prev_yaw = _next_yaw
	_prev_time = _next_time
	_next_pos = Vector3(last_mw_x, float(pose.get("z", 0.0)), -last_mw_y)
	_next_yaw = last_mw_yaw
	_next_time = t_sim
	if not _has_state:
		_has_state = true
		_prev_pos = _next_pos
		_prev_yaw = _next_yaw
		_prev_time = t_sim - interp_delay
		position = _next_pos
		rotation.y = _next_yaw
	_apply_wheel_spin(entity.get("joints", {}))
	_apply_arm_joints(entity.get("joints", {}))


func _apply_wheel_spin(joints: Variant) -> void:
	"""F6: spin drive-wheel meshes from hinge joint angles (MW +Y axle → Godot +Z)."""
	if use_kenney_car:
		return
	if typeof(joints) != TYPE_DICTIONARY:
		return
	ensure_planar_cart_visual()
	var body := get_node_or_null("Body")
	if body == null:
		return
	var angles: Array = []
	for jn in _wheel_joint_names:
		if joints.has(jn):
			angles.append(float(joints[jn]))
	if angles.is_empty():
		for key in ["left_wheel_joint", "right_wheel_joint"]:
			if joints.has(key):
				angles.append(float(joints[key]))
	var wi := 0
	for child in body.get_children():
		if not str(child.name).begins_with("Wheel_"):
			continue
		if wi >= angles.size():
			break
		# Rest Rx(90) then spin about mesh +Y (= axle after rest). Do NOT set
		# rotation.y — that is Godot up (yaw), which looks like a turntable.
		var angle := float(angles[wi])
		(child as Node3D).basis = Basis(Vector3.RIGHT, PI * 0.5) * Basis(Vector3.UP, angle)
		wi += 1


func _process(_delta: float) -> void:
	if not _has_state or _prev_time < 0.0:
		return
	var span := _next_time - _prev_time
	if span <= 0.0:
		# Degenerate timestamps: snap to latest authority pose.
		position = _next_pos
		rotation.y = _next_yaw
		return
	var render_time := _sim_clock() - interp_delay
	var alpha := clampf((render_time - _prev_time) / span, 0.0, 1.0)
	position = _prev_pos.lerp(_next_pos, alpha)
	rotation.y = _prev_yaw + (_next_yaw - _prev_yaw) * alpha


func _sim_clock() -> float:
	# Extrapolate forward from the last known sim time using wall clock,
	# so interpolation keeps moving between 20 Hz updates.
	return _sim_now + (Time.get_ticks_msec() / 1000.0 - _wall_at_last_state)
